#
# XRay Detector
# v1.0.0-snapshot
logger: true # Save logs into a file.
debug: false # only enable for developing: this will spam the console.

database:
  crash-shutdown: true # shutdown the server if databases are down.
  type: 'SQLITE' #SQLITE or MYSQL (coming soon)
  username: 'root'
  password: 'password'
  address: '127.0.0.1'
  db_name: 'minecraft'
  port: 3306

analysis:
  interval: 10 # how often the database should be scanned for cheaters, in minutes.